___
<img style="float: right; margin: 0px 0px 15px 15px;" src="https://www.carrerasenlinea.mx/logos/original/logo-instituto-tecnologico-y-de-estudios-superiores-de-occidente.png" width="150px" height="100px" />

# Microestructuras y Sistemas de Trading
## Laboratorio 4
### Equipo T

## <font color="navy">  "ANÁLISIS FUNDAMENTAL"
    
* <font color="black">**INTEGRANTE 1 :**</font> Hannia Cecilia Lomelí Salado
* <font color="black">**INTEGRANTE 2 :**</font> Tere Castillo
* <font color="black">**INTEGRANTE 3 :**</font> Marysol Cantarero Velazquez Del Valle 
* <font color="black">**INTEGRANTE 4 :**</font> Gaspar Benitez Fregoso

### <font color = navy> SITUACIÓN
En el mercado de Forex es ampliamente utilizado el "Calendario Económico" el cual es aquel que incorpora información de las principales economíad del mundo. Esta información se utiliza para realizar distintos análisis.

### <font color = navy> OBJETIVO
Describir los efectos cuantitativos en el precio durante los comunicados de los indicadores macroeconómicos " Trade Balance EUR" y "Trade Balance USD", así como detectar oportunidades de inversión a partir de los resultados obtenidos. 
    
### <font color = navy> MARCO TEÓRICO
"Trade Balance EUR" = La Balanza comercial mide la diferencia de valor entre los bienes y servicios importados y exportados durante el período informado. Un número positivo indica que se exportaron más bienes y servicios que importados. Es decir si la lectura es positiva, EUR tiene un super hábit en la balanza comercial , de ser el caso contrario se tendría un déficit
    
"Trade Balance USD" = La Balanza comercial mide la diferencia de valor entre los bienes y servicios importados y exportados durante el período informado. Un número positivo indica que se exportaron más bienes y servicios que importados. Es decir si la lectura es positiva, USD tiene un super hábit en la balanza comercial , de ser el caso contrario se tendría un déficit

 Reglas de lectura indicadores = Ej: Si X indicador es positivo entonces se espera movimiento alcista) !!!

### <font color = navy> Procedimiento

Importando librerías

In [1]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [2]:
#CALENDARIO ECONÓMICO
cal_ec = pd.read_csv("calendario_economico.csv") # leen los datos del excel calendario economico
cal_ec['timestamp'] = [pd.to_datetime(cal_ec.iat[i,0]).tz_localize('GMT') for i in range (len(cal_ec))]
cal_ec['timestamp'] = pd.to_datetime(cal_ec['timestamp'],format='%Y-%m-%d')
# iat ayuda a agarrar solo un valor de un dataframe
# tz_localize, ubica en un index de un dataframe la zona horaria(en este caso 'GMT')
cal_ec.head() #MES/DIA

,timestamp,Currency,Name,Country,Volatility,actual,previous,consensus
0,2009-01-05 09:30:00+00:00,EUR,Sentix Investor Confidence,European Monetary Union,1,-34.4,-42.3,NaN
1,2009-01-05 15:00:00+00:00,USD,Construction Spending (MoM),United States,1,-1.2,-0.4,-1.3
2,2009-01-06 08:55:00+00:00,EUR,Markit Services PMI,Germany,1,46.6,46.4,46.4
3,2009-01-06 09:00:00+00:00,EUR,Markit Services PMI,European Monetary Union,0,42.1,42.0,42.0
4,2009-01-06 10:00:00+00:00,EUR,Consumer Price Index (YoY),European Monetary Union,2,1.6,2.1,1.8

In [3]:
# PRECIOS HISTÓRICOS (2019) (para hacer pruebas iniciales)
precios = pd.read_csv("precios_historicos_eurusd.csv") #Lectura de datos
precios['timestamp'] = [pd.to_datetime(precios.iat[i,0]).tz_localize('GMT') for i in range (len(precios))] 
# iat ayuda a agarrar solo un valor de un dataframe
# tz_localize, ubica en un index de un dataframe la zona horaria(en este caso 'GMT')
precios.head() #MES/DIA

                  timestamp     open     high      low    close
0 2009-01-06 05:00:00+00:00  1.35564  1.35565  1.35383  1.35439
1 2009-01-06 05:05:00+00:00  1.35443  1.35489  1.35424  1.35474
2 2009-01-06 05:10:00+00:00  1.35480  1.35552  1.35439  1.35539
3 2009-01-06 05:15:00+00:00  1.35545  1.35549  1.35101  1.35101
4 2009-01-06 05:20:00+00:00  1.35101  1.35130  1.35021  1.35086

In [4]:
EUR = pd.DataFrame() #data frames vacios
USD = pd.DataFrame() #data frames vacios
for i in range(len(cal_ec)):
    d = cal_ec.index[i]
    if cal_ec['Name'][i] == "Trade Balance EUR":
        d=cal_ec.index[i]
        EUR[d] = cal_ec.iloc[i]
    elif cal_ec['Name'][i] == "Trade Balance":
        d=cal_ec.index[i]
        USD[d] = cal_ec.iloc[i]
EUR = EUR.T; EUR = EUR.reset_index(drop=True)
USD = USD.T; USD = USD.reset_index(drop=True)

In [5]:
EUR.head()

,timestamp,Currency,Name,Country,Volatility,actual,previous,consensus
0,2011-01-07 07:45:00+00:00,EUR,Trade Balance EUR,France,1,-4.1,NaN,NaN
1,2011-02-08 07:45:00+00:00,EUR,Trade Balance EUR,France,1,-5.1,-4.1,NaN
2,2011-03-08 06:45:00+00:00,EUR,Trade Balance EUR,France,1,-6.1,-5.1,NaN
3,2011-04-07 06:45:00+00:00,EUR,Trade Balance EUR,France,1,-6.4,-6.1,NaN
4,2011-05-06 06:45:00+00:00,EUR,Trade Balance EUR,France,1,-5.906,-6.4,NaN

In [6]:
USD.head()

,timestamp,Currency,Name,Country,Volatility,actual,previous,consensus
0,2009-01-13 13:30:00+00:00,USD,Trade Balance,United States,3,-41.58,-56.69,-51.4
1,2009-02-11 13:30:00+00:00,USD,Trade Balance,United States,3,-39.9,-41.58,-35.9
2,2009-03-13 12:30:00+00:00,USD,Trade Balance,United States,3,-36.2,-39.9,-38
3,2009-04-09 12:30:00+00:00,USD,Trade Balance,United States,3,-26.13,-36.2,-36.7
4,2009-05-12 12:30:00+00:00,USD,Trade Balance,United States,3,-28.53,-26.13,-28.9

Para las filas que no tienen Consensus, se usará Previous como Consensus

In [7]:
EUR.head()

,timestamp,Currency,Name,Country,Volatility,actual,previous,consensus
0,2011-01-07 07:45:00+00:00,EUR,Trade Balance EUR,France,1,-4.1,NaN,NaN
1,2011-02-08 07:45:00+00:00,EUR,Trade Balance EUR,France,1,-5.1,-4.1,NaN
2,2011-03-08 06:45:00+00:00,EUR,Trade Balance EUR,France,1,-6.1,-5.1,NaN
3,2011-04-07 06:45:00+00:00,EUR,Trade Balance EUR,France,1,-6.4,-6.1,NaN
4,2011-05-06 06:45:00+00:00,EUR,Trade Balance EUR,France,1,-5.906,-6.4,NaN

In [8]:
EUR['consensus'][0] = EUR['previous'][0]
for i in range(len(EUR['consensus'])-1): #ciclo for para rellenar los datos vacios de consensus con los datos de previous
    strEUR = str(EUR['consensus'][i+1])
    strUSD = str(USD['consensus'][i])
    if strEUR == 'nan':
        EUR['consensus'][i+1] = EUR['previous'][i]
    if strUSD == 'nan':
        USD['consensus'][i] = USD['previous'][i-1]

Clasificación de las observaciones de los comunicados según el siguiente criterio:

    oA Actual >= Consensus >= Previous
    oB Actual >= Consensus < Previous
    oC Actual < Consensus >= Previous
    oD Actual < Consensus < Previous

In [23]:
def clasificacion(indicador): #funcion de creacion de esenarios 
    indicador['escenario'] = '0'
    for i in range(len(EUR['actual'])):
        if str(indicador['actual'][i] >= indicador['consensus'][i] >= indicador['previous'][i]) == 'True':
            indicador['escenario'][i] = 'A'
        if str(indicador['actual'][i] >= indicador['consensus'][i] < indicador['previous'][i]) == 'True':
            indicador['escenario'][i] = 'B'
        if str(indicador['actual'][i] < indicador['consensus'][i] >= indicador['previous'][i]) == 'True':
            indicador['escenario'][i] = 'C'
        if str(EUR['actual'][i] < indicador['consensus'][i] < indicador['previous'][i]) == 'True':
            indicador['escenario'][i] = 'D'
    return(indicador)
EUR = clasificacion(EUR)
USD = clasificacion(USD)

In [24]:
# Revisar NAN y Escenarios
# FALTA BUSCAR LAS FECHAS DE CALENDARIO ECONOMICO EN PRECIOS!!
# Metricas
# Graficar Metricas escogiendo un escenario

In [25]:
EUR.head() #DIA/MES

,timestamp,Currency,Name,Country,Volatility,actual,previous,consensus,escenario
0,2011-01-07 07:45:00+00:00,EUR,Trade Balance EUR,France,1,-4.1,NaN,NaN,0
1,2011-02-08 07:45:00+00:00,EUR,Trade Balance EUR,France,1,-5.1,-4.1,NaN,0
2,2011-03-08 06:45:00+00:00,EUR,Trade Balance EUR,France,1,-6.1,-5.1,-4.1,C
3,2011-04-07 06:45:00+00:00,EUR,Trade Balance EUR,France,1,-6.4,-6.1,-5.1,C
4,2011-05-06 06:45:00+00:00,EUR,Trade Balance EUR,France,1,-5.906,-6.4,-6.1,A

In [12]:
precios.head() #MES/DIA

                  timestamp     open     high      low    close
0 2009-01-06 05:00:00+00:00  1.35564  1.35565  1.35383  1.35439
1 2009-01-06 05:05:00+00:00  1.35443  1.35489  1.35424  1.35474
2 2009-01-06 05:10:00+00:00  1.35480  1.35552  1.35439  1.35539
3 2009-01-06 05:15:00+00:00  1.35545  1.35549  1.35101  1.35101
4 2009-01-06 05:20:00+00:00  1.35101  1.35130  1.35021  1.35086

In [13]:
USD.head() # MES/DIA

,timestamp,Currency,Name,Country,Volatility,actual,previous,consensus,escenario
0,2009-01-13 13:30:00+00:00,USD,Trade Balance,United States,3,-41.58,-56.69,-51.4,A
1,2009-02-11 13:30:00+00:00,USD,Trade Balance,United States,3,-39.9,-41.58,-35.9,C
2,2009-03-13 12:30:00+00:00,USD,Trade Balance,United States,3,-36.2,-39.9,-38,A
3,2009-04-09 12:30:00+00:00,USD,Trade Balance,United States,3,-26.13,-36.2,-36.7,B
4,2009-05-12 12:30:00+00:00,USD,Trade Balance,United States,3,-28.53,-26.13,-28.9,B

In [19]:
intervalos = []
for i in range(0, len(EUR.index)):
    print(i)
    g = np.where(precios['timestamp'] == EUR['timestamp'][i])[0]
    print(g)
    precios.iloc[g-6:g+7]
intervalos[0]

0
[153135]

TypeError: cannot do slice indexing on <class 'pandas.core.indexes.range.RangeIndex'> with these indexers [[153129]] of <class 'numpy.ndarray'>

In [22]:
intervalos = []
for i in range(len(USD.index)):
    g= np.where(precios['timestamp'] == USD.index[i])[0][0]
    print(i)
    precios.iloc[g-6:g+7]
intervalos[1]

IndexError: index 0 is out of bounds for axis 0 with size 0

In [ ]:
EUR['timestamp'][3]

In [ ]:
g= np.where(precios['timestamp'] == EUR['timestamp'][3])[0][0]
precios['timestamp'][g]

In [ ]:
EUR.tail()

In [ ]:
intervalos = []
for i in range(len(precios)-12):
    intervalos.append(precios.iloc[i:i+13])

In [ ]:
Direccion =[]
Pips_Alcistas= []
Pips_Bajistas= []
Volatilidad= []
for i in range(len(intervalos)):
    Direccion.append(intervalos[i].iloc[12]['close'] - intervalos[i].iloc[6]['open'])
    #Pips_Alcistas.append(intervalos[0].iloc[12]['high'] - intervalos[0].iloc[6]['open'])
    #Pips_Bajistas.append(intervalos[0].iloc[12]['high'] - intervalos[0].iloc[6]['open'])
    #Volatilidad.append(intervalos[0].iloc[12]['high'] - intervalos[0].iloc[6]['open'])

In [ ]:
intervalos[0]