___
<img style="float: right; margin: 0px 0px 15px 15px;" src="https://www.carrerasenlinea.mx/logos/original/logo-instituto-tecnologico-y-de-estudios-superiores-de-occidente.png" width="150px" height="100px" />

# Microestructuras y Sistemas de Trading
## Laboratorio 4
### Equipo T

## <font color="navy">  "ANÁLISIS FUNDAMENTAL"
    
* <font color="black">**INTEGRANTE 1 :**</font> Hannia Cecilia Lomelí Salado
* <font color="black">**INTEGRANTE 2 :**</font> Tere Castillo
* <font color="black">**INTEGRANTE 3 :**</font> Marysol Cantarero Velazquez Del Valle 
* <font color="black">**INTEGRANTE 4 :**</font> Gaspar Benitez Fregoso

### <font color = navy> SITUACIÓN
En el mercado de Forex es ampliamente utilizado el "Calendario Económico" el cual es aquel que incorpora información de las principales economíad del mundo. Esta información se utiliza para realizar distintos análisis.

### <font color = navy> OBJETIVO
Describir los efectos cuantitativos en el precio durante los comunicados de los indicadores macroeconómicos " Trade Balance EUR" y "Trade Balance USD", así como detectar oportunidades de inversión a partir de los resultados obtenidos. 
    
### <font color = navy> MARCO TEÓRICO
"Trade Balance EUR" = La Balanza comercial mide la diferencia de valor entre los bienes y servicios importados y exportados durante el período informado. Un número positivo indica que se exportaron más bienes y servicios que importados. Es decir si la lectura es positiva, EUR tiene un super hábit en la balanza comercial , de ser el caso contrario se tendría un déficit
    
"Trade Balance USD" = La Balanza comercial mide la diferencia de valor entre los bienes y servicios importados y exportados durante el período informado. Un número positivo indica que se exportaron más bienes y servicios que importados. Es decir si la lectura es positiva, USD tiene un super hábit en la balanza comercial , de ser el caso contrario se tendría un déficit

 Reglas de lectura indicadores = Ej: Si X indicador es positivo entonces se espera movimiento alcista) !!!

### <font color = navy> Procedimiento

Importando librerías

In [1]:
import numpy as np
import pandas as pd

In [2]:
#CALENDARIO ECONÓMICO
cal_ec = pd.read_excel("calendario_economico.xlsx")
cal_ec['timestamp'] = pd.to_datetime(cal_ec['timestamp'])
cal_ec.index = cal_ec['timestamp'] ; cal_ec = cal_ec.drop("timestamp",axis=1)
cal_ec.head()

,Currency,Name,Country,Volatility,actual,previous,consensus
timestamp,,,,,,,
2009-05-01 09:30:00,EUR,Sentix Investor Confidence,European Monetary Union,1,-34.4,-42.3,NaN
2009-05-01 15:00:00,USD,Construction Spending (MoM),United States,1,-1.2,-0.4,-1.3
2009-06-01 08:55:00,EUR,Markit Services PMI,Germany,1,46.6,46.4,46.4
2009-06-01 09:00:00,EUR,Markit Services PMI,European Monetary Union,0,42.1,42.0,42.0
2009-06-01 10:00:00,EUR,Consumer Price Index (YoY),European Monetary Union,2,1.6,2.1,1.8

In [3]:
# PRECIOS HISTÓRICOS (2019) (para hacer pruebas iniciales)
precios = pd.read_excel("precios_historicos_eurusd_2019.xlsx")
precios['timestamp'] = pd.to_datetime(precios['timestamp'])
precios.index = precios['timestamp'] ; precios = precios.drop("timestamp",axis=1)
precios.head()

                        open     high      low    close
timestamp
2019-01-01 22:00:00  1.14649  1.14658  1.14634  1.14658
2019-01-01 22:05:00  1.14658  1.14658  1.14635  1.14635
2019-01-01 22:10:00  1.14635  1.14636  1.14632  1.14632
2019-01-01 22:15:00  1.14632  1.14632  1.14632  1.14632
2019-01-01 22:20:00  1.14653  1.14653  1.14653  1.14653

In [4]:
EUR = pd.DataFrame()
USD = pd.DataFrame()
for i in range(len(cal_ec)):
    d = cal_ec.index[i]
    if cal_ec['Name'][i] == "Trade Balance EUR":
        d=cal_ec.index[i]
        EUR[d] = cal_ec.iloc[i]
    elif cal_ec['Name'][i] == "Trade Balance":
        d=cal_ec.index[i]
        USD[d] = cal_ec.iloc[i]
EUR = EUR.T
USD = USD.T

In [5]:
EUR.head()

,Currency,Name,Country,Volatility,actual,previous,consensus
2011-08-02 07:45:00,EUR,Trade Balance EUR,France,1,-5.1,-4.1,NaN
2011-08-03 06:45:00,EUR,Trade Balance EUR,France,1,-6.1,-5.1,NaN
2011-07-04 06:45:00,EUR,Trade Balance EUR,France,1,-6.4,-6.1,NaN
2011-06-05 06:45:00,EUR,Trade Balance EUR,France,1,-5.906,-6.4,NaN
2011-08-06 06:45:00,EUR,Trade Balance EUR,France,1,-7.2,-5.906,NaN

In [6]:
USD.head()

,Currency,Name,Country,Volatility,actual,previous,consensus
2009-01-13 13:30:00,USD,Trade Balance,United States,3,-41.58,-56.69,-51.4
2009-11-02 13:30:00,USD,Trade Balance,United States,3,-39.9,-41.58,-35.9
2009-03-13 12:30:00,USD,Trade Balance,United States,3,-36.2,-39.9,-38
2009-09-04 12:30:00,USD,Trade Balance,United States,3,-26.13,-36.2,-36.7
2009-12-05 12:30:00,USD,Trade Balance,United States,3,-28.53,-26.13,-28.9

Para las filas que no tienen Consensus, se usará Previous como Consensus

In [7]:
for i in range(len(EUR['consensus'])):
    strEUR = str(EUR['consensus'][i])
    strUSD = str(USD['consensus'][i])
    if strEUR == 'nan':
        EUR['consensus'][i] = EUR['previous'][i-1]
    if strUSD == 'nan':
        USD['consensus'][i] = USD['previous'][i-1]

Clasificación de las observaciones de los comunicados según el siguiente criterio:

    oA Actual >= Consensus >= Previous
    oB Actual >= Consensus < Previous
    oC Actual < Consensus >= Previous
    oD Actual < Consensus < Previous

In [8]:
def clasificacion(indicador):
    indicador['escenario'] = '0'
    for i in range(len(EUR['actual'])):
        if str(indicador['actual'][i] >= indicador['consensus'][i] >= indicador['previous'][i]) == 'True':
            indicador['escenario'][i] = 'A'
        if str(indicador['actual'][i] >= indicador['consensus'][i] < indicador['previous'][i]) == 'True':
            indicador['escenario'][i] = 'B'
        if str(indicador['actual'][i] < indicador['consensus'][i] >= indicador['previous'][i]) == 'True':
            indicador['escenario'][i] = 'C'
        if str(EUR['actual'][i] < indicador['consensus'][i] < indicador['previous'][i]) == 'True':
            indicador['escenario'][i] = 'D'
    return(indicador)
EUR = clasificacion(EUR)
USD = clasificacion(USD)

In [ ]:
#FALTA BUSCAR LAS FECHAS DE CALENDARIO ECONOMICO EN PRECIOS!!

In [9]:
intervalos = []
for i in range(len(precios)-12):
    intervalos.append(precios.iloc[i:i+13])

In [ ]:
Direccion =[]
Pips_Alcistas= []
Pips_Bajistas= []
Volatilidad= []
for i in range(len(intervalos)):
    Direccion.append(intervalos[i].iloc[12]['close'] - intervalos[i].iloc[6]['open'])
    #Pips_Alcistas.append(intervalos[0].iloc[12]['high'] - intervalos[0].iloc[6]['open'])
    #Pips_Bajistas.append(intervalos[0].iloc[12]['high'] - intervalos[0].iloc[6]['open'])
    #Volatilidad.append(intervalos[0].iloc[12]['high'] - intervalos[0].iloc[6]['open'])

In [10]:
intervalos[0]

                        open     high      low    close
timestamp
2019-01-01 22:00:00  1.14649  1.14658  1.14634  1.14658
2019-01-01 22:05:00  1.14658  1.14658  1.14635  1.14635
2019-01-01 22:10:00  1.14635  1.14636  1.14632  1.14632
2019-01-01 22:15:00  1.14632  1.14632  1.14632  1.14632
2019-01-01 22:20:00  1.14653  1.14653  1.14653  1.14653
2019-01-01 22:25:00  1.14652  1.14652  1.14630  1.14648
2019-01-01 22:30:00  1.14653  1.14653  1.14616  1.14646
2019-01-01 22:35:00  1.14646  1.14647  1.14644  1.14646
2019-01-01 22:40:00  1.14646  1.14650  1.14620  1.14637
2019-01-01 22:45:00  1.14638  1.14638  1.14624  1.14632
2019-01-01 22:50:00  1.14632  1.14648  1.14618  1.14648
2019-01-01 22:55:00  1.14648  1.14650  1.14621  1.14641
2019-01-01 23:00:00  1.14640  1.14672  1.14579  1.14655